import { Footer } from "../components/shared/footer";
import { Header } from "../components/shared/header";
import "./global.css";

export const metadata = {
  description: "Generated by create-nx-workspace",
  title: "Welcome to web",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
